# Generated by Django 4.1.7 on 2023-07-26 06:51

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('date_of_birth', models.DateField()),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subscription', models.IntegerField(choices=[(0, 'Single Class 3'), (1, 'Single Class 5'), (2, 'Double Classes'), (3, 'Triple Classes')])),
                ('joined', models.DateField()),
                ('due_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('discipline', models.CharField(choices=[('B', 'Boxing'), ('KB', 'MMA-KickBoxing'), ('W', 'MMA-Wrestling'), ('SC', 'Strength and Conditioning'), ('Y', 'Yoga'), ('PT', 'Personal Training'), ('K', 'Kids')], default='B', max_length=2)),
            ],
        ),
    ]
