# Generated by Django 4.1.7 on 2023-07-28 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='showed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
