# Generated by Django 4.1.7 on 2023-08-01 06:31

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_contact_created_alter_contact_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=125)),
                ('date_of_birth', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('trainer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percent', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('joined', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='number_of_classes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=125),
        ),
        migrations.AlterField(
            model_name='client',
            name='subscription',
            field=models.IntegerField(choices=[(0, 'Single Class-3'), (1, 'Single Class-5'), (2, 'Double Classes'), (3, 'Triple Classes')], default=0),
        ),
    ]
