# Generated by Django 4.1.7 on 2023-08-01 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_trainer_remove_client_name_client_active_and_more'),
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='clients',
            field=models.ManyToManyField(related_name='classes', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='course',
            name='trainers',
            field=models.ManyToManyField(related_name='courses', to='accounts.trainer'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('SU', 'Sunday')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gym.course')),
            ],
            options={
                'unique_together': {('day', 'time')},
            },
        ),
    ]
